image: node:13.0.1

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run build
  - mkdir public
  - cp -r * dist/. public
  artifacts:
    paths:
    - public
  only:
    - master
